embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"background\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "size {\n"
  "  x: 600.0\n"
  "  y: 1256.0\n"
  "}\n"
  "size_mode: SIZE_MODE_MANUAL\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/sprites/sprites.atlas\"\n"
  "}\n"
  ""
}
